# BiT (Big Transfer) with Standard CIFAR-100 Non-IID Configuration
# Uses Dirichlet distribution (alpha=0.5) for non-IID split
# Optimized for low-data regime with regularization

seed: 42
use_gpu: true
use_amp: false

data:
  dataset_name: cifar100  # Standard CIFAR-100
  data_dir: ./data
  num_clients: 10
  num_test_clients: 10
  batch_size: 64
  num_workers: 4
  pin_memory: true
  input_size: 224
  verbose: false
  imagenet_style: true  # Use ImageNet transforms for BiT
  # Non-IID specific settings
  data_split: non_iid  # Use non-IID split with Dirichlet distribution
  alpha: 0.5  # Dirichlet parameter (smaller = more heterogeneous)
  seed: 42
  augmentations:
    horizontal_flip:
      enabled: true
      prob: 0.5
    random_rotation:
      enabled: true
      degrees: 20
    random_resized_crop:
      enabled: true
      scale_min: 0.4
    color_jitter:
      enabled: true
      brightness: 0.3
      contrast: 0.3
      saturation: 0.3
      hue: 0.1
    random_erasing:
      enabled: true
      prob: 0.3
    mixup:
      enabled: false
      alpha: 0.2
      prob: 0.5
    cutmix:
      enabled: false
      alpha: 1.0
      prob: 0.5

model:
  model_name: bit_m_r50x1
  num_classes: 100
  pretrained: true
  freeze_backbone: true
  lora:
    enabled: true
    r: 8
    alpha: 16
    dropout: 0.1

training:
  epochs: 3
  lr: 0.0001
  momentum: 0.9
  weight_decay: 0.001
  scheduler: cosine
  warmup_epochs: 0
  label_smoothing: 0.1
  gradient_clip: 1.0
  optimizer: sgd

federated:
  num_rounds: 200
  num_clients: 10
  client_fraction: 0.3
  aggregation_method: fedsa
  checkpoint_freq: 25
  exclude_bn_from_agg: true

privacy:
  enable_privacy: false
  epsilon: 8.0
  delta: 1e-05
  max_grad_norm: 0.5
  noise_multiplier: 1.0
  target: lora_A
  use_opacus_accounting: true

evaluation:
  eval_freq: 2
  metric: accuracy
  save_best_model: true

experiment:
  name: BiT_CIFAR100_NonIID_FedSA
  output_dir: experiments/quickstart_bit_tff/non-iid
  save_history: true
  save_model: true
  log_interval: 10
  use_wandb: false
  wandb_project: bit-cifar100-fedsa-noniid
  wandb_entity: null

reproducibility:
  deterministic: false

advanced:
  personalized: true
  personalization_layers:
    - lora_B
    - head
  use_fbftl: false
  feature_extraction_rounds: 10
  server_lr: 1.0
  server_momentum: 0.9

communication:
  compress: false
  compression_ratio: 0.1
  quantization_bits: null
