# BiT (Big Transfer) with TFF CIFAR-100 Non-IID Configuration - FedAvg
# Optimized for low-data regime (100 samples/client)
# FedAvg: Shares ALL trainable parameters (LoRA A + B + classifier)

seed: 42
use_gpu: true
use_amp: false

data:
  dataset_name: cifar100
  data_dir: ./data
  num_clients: 10
  num_test_clients: 30
  batch_size: 32  # Reduced for better generalization
  num_workers: 4
  pin_memory: true
  input_size: 224
  verbose: false
  augmentations:
    horizontal_flip:
      enabled: true
      prob: 0.5
    random_rotation:
      enabled: true
      degrees: 20
    random_resized_crop:
      enabled: true
      scale_min: 0.4
    color_jitter:
      enabled: true
      brightness: 0.3
      contrast: 0.3
      saturation: 0.3
      hue: 0.1
    random_erasing:
      enabled: true
      prob: 0.3
    mixup:
      enabled: false
      alpha: 0.2
      prob: 0.5
    cutmix:
      enabled: false
      alpha: 1.0
      prob: 0.5

model:
  model_name: bit_m_r50x1
  num_classes: 100
  pretrained: true
  freeze_backbone: true
  lora:
    enabled: true
    r: 8
    alpha: 16
    dropout: 0.2

training:
  epochs: 3  # Reduced to prevent overfitting
  lr: 0.0001  # Low LR for small dataset
  momentum: 0.9
  weight_decay: 0.001  # Strong regularization
  scheduler: cosine
  warmup_epochs: 0
  label_smoothing: 0.1
  gradient_clip: 1.0
  optimizer: sgd

federated:
  num_rounds: 200
  num_clients: 10
  client_fraction: 1.0
  aggregation_method: fedavg  # FedAvg: Share ALL parameters
  checkpoint_freq: 25
  exclude_bn_from_agg: true

privacy:
  enable_privacy: false
  epsilon: 8.0
  delta: 1e-05
  max_grad_norm: 0.5
  noise_multiplier: 1.0
  target: lora_A
  use_opacus_accounting: true

evaluation:
  eval_freq: 5
  metric: accuracy
  save_best_model: true

experiment:
  name: BiT_TFF_CIFAR100_NonIID_FedAvg_LowLR
  output_dir: experiments/quickstart_bit_tff
  save_history: true
  save_model: true
  log_interval: 10
  use_wandb: false
  wandb_project: bit-tff-fedavg
  wandb_entity: null

reproducibility:
  deterministic: false

advanced:
  personalized: false  # FedAvg: No personalization, all params shared
  personalization_layers: []
  use_fbftl: false
  feature_extraction_rounds: 10
  server_lr: 1.0
  server_momentum: 0.9

communication:
  compress: false
  compression_ratio: 0.1
  quantization_bits: null
