advanced:
  feature_extraction_rounds: 10
  personalization_layers: []
  personalized: false
  server_lr: 1.0
  server_momentum: 0.9
  use_fbftl: false
communication:
  compress: false
  compression_ratio: 0.1
  quantization_bits: null
data:
  alpha: 0.5
  augmentations:
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      enabled: true
      hue: 0.1
      saturation: 0.2
    cutmix:
      alpha: 1.0
      enabled: false
      prob: 0.5
    horizontal_flip:
      enabled: true
      prob: 0.5
    mixup:
      alpha: 0.2
      enabled: false
      prob: 0.5
    random_crop:
      enabled: true
      padding: 4
    random_erasing:
      enabled: false
      prob: 0.5
    random_rotation:
      degrees: 15
      enabled: true
  batch_size: 128
  data_dir: ./data
  data_split: iid
  dataset_name: cifar100
  model_type: resnet
  num_clients: 10
  num_workers: 4
  verbose: false
evaluation:
  eval_freq: 5
  metric: accuracy
  patience: 30
  save_best_model: true
experiment:
  log_interval: 10
  name: ResNet18_CIFAR100_IID_FedAvg
  output_dir: experiments/fedavg_resnet18_iid
  save_history: true
  save_model: true
  use_wandb: false
  wandb_entity: null
  wandb_project: fedsa-ftl-resnet
federated:
  aggregation_method: fedavg
  checkpoint_freq: 25
  client_fraction: 1.0
  num_clients: 10
  num_rounds: 100
model:
  lora_alpha: 32
  lora_dropout: 0.1
  lora_r: 16
  model_name: resnet18
  num_classes: 100
  pretrained: true
privacy:
  delta: 1.0e-05
  enable_privacy: false
  epsilon: 8.0
  max_grad_norm: 0.5
  noise_multiplier: 1.0
  target: lora_A
  use_opacus_accounting: true
reproducibility:
  deterministic: false
seed: 42
training:
  epochs: 3
  gradient_clip: 1.0
  lr: 0.01
  microbatch_size: 8
  momentum: 0.9
  optimizer: sgd
  scheduler: cosine
  warmup_epochs: 5
  weight_decay: 0.0005
use_gpu: true