seed: 42
use_gpu: true
use_amp: false

data:
  dataset_name: cifar100
  data_dir: ./data
  num_clients: 5  # Reduced for Colab
  num_test_clients: 5
  batch_size: 32  # Reduced for memory
  num_workers: 2
  pin_memory: true
  input_size: 224
  verbose: false
  imagenet_style: true
  data_split: non_iid
  alpha: 0.1
  seed: 42
  augmentations:
    horizontal_flip:
      enabled: true
      prob: 0.5
    random_rotation:
      enabled: true
      degrees: 10
    random_resized_crop:
      enabled: true
      scale_min: 0.5

training:
  epochs: 3
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  scheduler: cosine

federated:
  num_rounds: 50  # Reduced for testing
  num_clients: 5
  client_fraction: 1.0
  aggregation_method: fedsa_custom_dp  # *** Use custom DP instead of Opacus ***
  checkpoint_freq: 10

# Privacy settings for custom DP (memory efficient)
privacy:
  enable_privacy: true
  epsilon: 8.0          # Privacy budget
  delta: 1.0e-05        # Privacy parameter
  max_grad_norm: 0.5    # Gradient clipping threshold
  noise_multiplier: 1.0 # Noise scale (actual_noise = noise_multiplier * max_grad_norm)

evaluation:
  eval_freq: 10
  metric: accuracy

experiment:
  name: BiT_CustomDP_Test
  output_dir: experiments/custom_dp_test
  save_history: true

reproducibility:
  deterministic: false

model:
  model_name: bit_m_r50x1  # Smaller model for Colab
  num_classes: 100
  pretrained: true
  freeze_backbone: true
  lora:
    enabled: true
    r: 4  # Reduced rank for memory
    alpha: 8
    dropout: 0.1
