seed: 42
use_gpu: true

data:
  dataset_name: mnist
  data_dir: ./data
  num_clients: 10
  num_test_clients: 10
  batch_size: 32
  num_workers: 4
  input_size: 224
  verbose: false
  data_split: iid
  alpha: 0.3

model:
  model_name: bit_s_r50x1
  num_classes: 10
  pretrained: true
  freeze_backbone: true
  lora:
    enabled: true
    r: 8
    alpha: 16
    dropout: 0.1

training:
  epochs: 3
  lr: 0.0001
  momentum: 0.9
  weight_decay: 0.001

federated:
  num_rounds: 100
  num_clients: 10
  client_fraction: 1.0
  aggregation_method: fedsa_shareA_dp
  checkpoint_freq: 25

privacy:
  enable_privacy: true
  epsilon: 2.0
  delta: 1.0e-05
  max_grad_norm: 0.5
  noise_multiplier: 3.8
  target: lora_A
  use_opacus_accounting: true

evaluation:
  eval_freq: 2

experiment:
  name: BiT_MNIST_AttackEval
  output_dir: experiments/bit_mnist_attack_eval

privacy_attacks:
  membership_inference:
    enabled: true
    attack_batch_size: 32
    max_member_batches: 10
    max_nonmember_batches: 10
    method: shadow
    shadow:
      lr: 0.05
      train_steps: 400
      batch_size: 32
      weight_decay: 0.0
      feature_set: [delta_l2, delta_abs_mean]
      feature_update_lr: 0.1
      feature_update_steps: 1
      normalize: true
  gradient_leakage:
    enabled: false
    attack_mode: trajectory
    trajectory_rounds: 4
    trajectory_min_rounds: 2
    trajectory_only: false
    optimization_steps: 400
    attack_lr: 0.25
    max_layers: 4
    optimize_labels: true
    l2_regularizer: 1.0e-4
    max_seconds: 12.0
