# Configuration for ResNet18 on CIFAR-100 with FedSA-FTL
# Lightweight model for faster training

# Random seed for reproducibility
seed: 42

# Device configuration
use_gpu: true

# Data configuration
data:
  dataset_name: cifar100
  data_dir: ./data
  num_clients: 10
  data_split: non_iid  # 'iid' or 'non_iid'
  alpha: 0.5  # Dirichlet parameter for non-IID split
  batch_size: 128  # Larger batch size for lighter model
  num_workers: 4
  model_type: resnet
  verbose: false
  
  # Data augmentation settings
  augmentations:
    horizontal_flip:
      enabled: true
      prob: 0.5
    
    random_rotation:
      enabled: true
      degrees: 15  # Slightly more rotation for ResNet18
    
    color_jitter:
      enabled: true  # Enable for ResNet18 to improve generalization
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    
    random_crop:
      enabled: true  # Enable for better generalization
      padding: 4
    
    random_erasing:
      enabled: false
      prob: 0.5
    
    mixup:
      enabled: false
      alpha: 0.2
      prob: 0.5
    
    cutmix:
      enabled: false
      alpha: 1.0
      prob: 0.5

# Model configuration
model:
  model_name: resnet18  # Lightweight ResNet variant
  num_classes: 100
  pretrained: true
  
  # LoRA configuration (higher rank for simpler model)
  lora_r: 16  # Higher rank for ResNet18
  lora_alpha: 32
  lora_dropout: 0.1

# Training configuration
training:
  epochs: 10  # More local epochs for lighter model
  lr: 0.01  # Higher learning rate for ResNet18
  momentum: 0.9
  weight_decay: 0.0005
  scheduler: cosine
  warmup_epochs: 2
  optimizer: sgd
  gradient_clip: 1.0
  microbatch_size: 8  # For DP per-sample clipping

# Federated learning configuration
federated:
  num_rounds: 150  # More rounds for simpler model
  num_clients: 10
  client_fraction: 1.0
  aggregation_method: fedsa_shareA_dp  # FedSA with DP on A matrices
  checkpoint_freq: 25

# Privacy configuration (DP-LoRA)
privacy:
  enable_privacy: true  # Enable DP for A matrices
  target: lora_A  # Apply DP only to A matrices
  epsilon: 8.0  # Privacy epsilon
  delta: 1e-5  # Privacy delta
  max_grad_norm: 0.5  # Gradient clipping threshold
  noise_multiplier: 1.0  # Noise multiplier for DP-SGD

# Evaluation configuration
evaluation:
  eval_freq: 5
  save_best_model: true
  metric: accuracy
  patience: 30

# Experiment configuration
experiment:
  name: ResNet18_CIFAR100_NonIID
  output_dir: experiments/quickstart_resnet
  save_model: true
  save_history: true
  log_interval: 10
  
  use_wandb: false
  wandb_project: fedsa-ftl-resnet
  wandb_entity: null

# Reproducibility settings
reproducibility:
  deterministic: false

# Communication efficiency settings
communication:
  compress: false
  compression_ratio: 0.1
  quantization_bits: null

# Advanced settings
advanced:
  use_fbftl: false
  feature_extraction_rounds: 10
  personalized: true
  personalization_layers: ['classifier', 'lora_B']
  server_lr: 0.01
  server_momentum: 0.9