# FedSA-FTL Configuration for CIFAR-10 with ViT

# Random seed for reproducibility
seed: 42

# Use GPU if available
use_gpu: true

# Experiment settings
experiment:
  name: fedsa_ftl_cifar10_vit
  description: "FedSA-FTL with frozen ViT backbone and LoRA head on CIFAR-10"
  output_dir: experiments/fedsa_ftl_cifar10_vit

# Model configuration
model:
  num_classes: 10
  model_name: "google/vit-base-patch16-224-in21k"  # Pre-trained ViT model
  lora_r: 8  # LoRA rank
  lora_alpha: 16  # LoRA scaling factor
  lora_dropout: 0.1  # LoRA dropout
  freeze_backbone: true  # Freeze backbone (FbFTL approach)

# Data configuration
data:
  data_dir: "./data"
  batch_size: 32
  num_workers: 2
  data_split: "non_iid"  # "iid" or "non_iid"
  alpha: 0.5  # Dirichlet distribution parameter for non-IID split
  verbose: true  # Print data distribution analysis

# Federated learning configuration
federated:
  num_clients: 10
  num_rounds: 100
  client_fraction: 0.3  # Fraction of clients selected per round
  checkpoint_freq: 10  # Save checkpoint every N rounds
  save_best_model: true
  aggregation_method: "fedavg"  # "fedavg" or "equal"

# Training configuration
training:
  local_epochs: 5
  learning_rate: 0.001  # 1e-3
  weight_decay: 0.0001  # 1e-4