# Single Client ViT Configuration without Advanced Augmentation
# For baseline comparison (no Mixup/CutMix)
# Total training = FL (local_epochs=5 × num_rounds=100 = 500 epochs)

seed: 42
use_gpu: true

experiment:
  name: "single_client_vit_tiny_no_augmented"
  description: "Single Client ViT-Tiny on CIFAR-100 - No Mixup baseline"
  output_dir: "experiments/single_client_no_augmented"

model:
  num_classes: 100
  model_name: "vit_small"  # Same as FL
  lora_r: 8               # Same as FL
  lora_alpha: 16           # Same as FL
  lora_dropout: 0.1       # Same as FL
  freeze_backbone: true   # Same as FL
  pretrained: true        # Same as FL

data:
  dataset_name: "cifar100"
  data_dir: "./data"
  batch_size: 32          # Same as FL
  num_workers: 2
  model_type: "vit"
  
  # Standard augmentation only (no Mixup/CutMix)
  augmentations:
    random_crop:
      enabled: true
      padding: 4
    horizontal_flip:
      enabled: true
      prob: 0.5
    color_jitter:
      enabled: true
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    random_rotation:
      enabled: true
      degrees: 15
    random_erasing:
      enabled: true
      prob: 0.25
      scale: [0.02, 0.33]
      ratio: [0.3, 3.3]
    # No Mixup/CutMix for baseline
    mixup:
      enabled: false
      alpha: 0.2
      prob: 0.5
    cutmix:
      enabled: false
      alpha: 1.0
      prob: 0.5
  
  verbose: false

training:
  epochs: 150               # Total training epochs (5 × 30 rounds)
  optimizer: "adamw"        # Same as FL
  learning_rate: 0.0001     # Same as FL (adjusted for single client)
  weight_decay: 0.01        # Same as FL
  betas: [0.9, 0.999]       # Same as FL
  eps: 1e-8                 # Same as FL
  grad_clip: 1.0            # Same as FL

evaluation:
  eval_freq: 25             # Evaluate every 25 epochs (equivalent to FL's 5-round intervals)
  eval_on_train: false
  eval_on_test: true
  save_predictions: false

reproducibility:
  deterministic: false
  benchmark: true

# Note: No federated or privacy sections needed for single client