name: fedsa-ftl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=1.9.0
  - torchvision
  - torchaudio
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - seaborn
  - jupyterlab
  - pip
  - pip:
    - transformers>=4.20.0
    - datasets
    - tokenizers
    - accelerate
    - peft
    - fvcore
